package:
  name: ros-galactic-ompl
  version: 1.5.2
source:
  git_url: https://github.com/ros-gbp/ompl-release.git
  git_rev: release/galactic/ompl/1.5.2-1
  folder: ros-galactic-ompl/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 1
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
    - sel(build_platform != target_platform): pkg-config
  host:
    - boost
    - cmake
    - eigen
    - python
    - ros-galactic-ros-environment
    - ros-galactic-ros-workspace
    - ros2-distro-mutex 0.1 galactic
    - sel(build_platform == target_platform): pkg-config
  run:
    - boost
    - eigen
    - flann
    - python
    - ros-galactic-ros-workspace
    - ros2-distro-mutex 0.1 galactic
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
