pool:
  vmImage: ubuntu-latest
trigger:
- buildbranch_linux
pr: none
stages:
- stage: stage_0
  jobs:
  - job: stage_0_job_0
    steps:
    - script: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/run_docker_build.sh
      env:
        ANACONDA_API_TOKEN: $(ANACONDA_API_TOKEN)
        CURRENT_RECIPES: ros-galactic-soccer-object-msgs
        DOCKER_IMAGE: condaforge/linux-anvil-comp7
      displayName: Build ros-galactic-soccer-object-msgs
