package:
  name: ros-galactic-bondcpp
  version: 3.0.1
source:
  git_url: https://github.com/ros2-gbp/bond_core-release.git
  git_rev: release/galactic/bondcpp/3.0.1-4
  folder: ros-galactic-bondcpp/src/work
  patches:
    - patch/ros-galactic-bondcpp.osx.patch

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 1
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
    - sel(build_platform != target_platform): pkg-config
  host:
    - python
    - ros-galactic-ament-cmake
    - ros-galactic-ament-lint-auto
    - ros-galactic-ament-lint-common
    - ros-galactic-bond
    - ros-galactic-rclcpp
    - ros-galactic-rclcpp-lifecycle
    - ros-galactic-ros-environment
    - ros-galactic-ros-workspace
    - ros-galactic-smclib
    - ros2-distro-mutex 0.1 galactic
    - sel(build_platform == target_platform): pkg-config
  run:
    - python
    - ros-galactic-bond
    - ros-galactic-rclcpp
    - ros-galactic-rclcpp-lifecycle
    - ros-galactic-ros-workspace
    - ros-galactic-smclib
    - ros2-distro-mutex 0.1 galactic
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
