package:
  name: ros-galactic-cyclonedds
  version: 0.8.0
source:
  git_url: https://github.com/ros2-gbp/cyclonedds-release.git
  git_rev: release/galactic/cyclonedds/0.8.0-6
  folder: ros-galactic-cyclonedds/src/work
  patches:
    - patch/ros-galactic-cyclonedds.patch

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 2
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
    - sel(build_platform != target_platform): ros-galactic-cyclonedds
  host:
    - bison
    - cunit
    - openssl
    - python
    - ros-galactic-iceoryx-binding-c
    - ros-galactic-iceoryx-posh
    - ros-galactic-iceoryx-utils
    - ros-galactic-ros-environment
    - ros-galactic-ros-workspace
    - ros2-distro-mutex 0.1 galactic
  run:
    - openssl
    - python
    - ros-galactic-iceoryx-binding-c
    - ros-galactic-iceoryx-posh
    - ros-galactic-iceoryx-utils
    - ros-galactic-ros-workspace
    - ros2-distro-mutex 0.1 galactic
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
